name: Unit tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run with tmate'
        required: false
        default: false
env:
  MPIEXE: "mpirun --oversubscribe"
  CC: mpicc
  INSTDIR: ${{ github.workspace }}/install/
  BINDIR: ${{ github.workspace }}/install/bin
  GSDIR: ${{ github.workspace }}/gslib/install
jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout actions
      uses: actions/checkout@v6
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ inputs.debug_enabled }}
    - name: Install apt dependencies
      run: |
        sudo apt -y update
        sudo apt install -y openmpi-bin libopenmpi-dev
        sudo apt install -y build-essential cmake
        sudo apt install -y clang-format
    - name: Build parRSB and run tests
      run: |
        MPIOPTS="--oversubscribe" ./bin/test.sh
