name: Unit tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run with tmate'
        required: false
        default: false
env:
  MPIEXE: "mpirun --oversubscribe"
  CC: mpicc
  INSTDIR: ${{ github.workspace }}/install/
  BINDIR: ${{ github.workspace }}/install/bin
  GSDIR: ${{ github.workspace }}/gslib/install
jobs:
  install:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout actions
      uses: actions/checkout@v6
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ inputs.debug_enabled }}
    - name: Install apt dependencies
      run: |
        sudo apt -y update
        sudo apt install -y openmpi-bin libopenmpi-dev
        sudo apt install -y build-essential cmake
    - name: Build gslib
      run: |
        git clone https://github.com/thilinarmtb/gslib.git
        cmake -B ./gslib/build -S ./gslib -DCMAKE_INSTALL_PREFIX=${GSDIR}
        cmake --build ./gslib/build --target install
    - name: Install parRSB
      run: |
        cmake -B build -S . -DCMAKE_INSTALL_PREFIX=${INSTDIR} -Dgs_DIR=${GSDIR}/lib/cmake/gs
        cmake --build build --target install
    - name: Upload parRSB workspace
      uses: actions/upload-artifact@v6
      with:
        name: assets
        include-hidden-files: true
        path: |
          ./install
          ./gslib/install
        if-no-files-found: error
  unit:
    runs-on: ubuntu-latest
    needs: install
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        np: [1, 2, 3, 4]
    steps:
    - name: Checkout actions
      uses: actions/checkout@v6
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ inputs.debug_enabled }}
    - name: Install apt dependencies
      run: |
        sudo apt -y update
        sudo apt install -y openmpi-bin libopenmpi-dev
        sudo apt install -y build-essential cmake
    - name: Download parRSB workspace
      uses: actions/download-artifact@v6
      with:
        name: assets
        path: ${{ github.workspace }}
    - name: Make binaries executable
      run: |
        chmod -R +x ${BINDIR}/*
    - name: Test Laplacian matrix
      run: |
        ${MPIEXE} -np ${{ matrix.np }} ${BINDIR}/parrsb_000_graph_laplacian
    - name: Test Laplacian operator
      run: |
        ${MPIEXE} -np ${{ matrix.np }} ${BINDIR}/parrsb_050_graph_laplacian_op
    - name: Test Laplacian eigenvalues
      run: |
        ${MPIEXE} -np ${{ matrix.np }} ${BINDIR}/parrsb_100_graph_eigenvalues
    - name: Block to allow inspecting failures
      run: sleep 120m
      if: ${{ failure() && inputs.debug_enabled }}
  cmake:
    runs-on: ubuntu-latest
    needs: install
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout actions
      uses: actions/checkout@v6
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ inputs.debug_enabled }}
    - name: Install apt dependencies
      run: |
        sudo apt -y update
        sudo apt install -y openmpi-bin libopenmpi-dev
        sudo apt install -y build-essential cmake
    - name: Download parRSB workspace
      uses: actions/download-artifact@v6
      with:
        name: assets
        path: ${{ github.workspace }}
    - name: Test exported CMake targets
      run: |
        cd ./test/cmake/find_package
        cmake -S . -B build -DCMAKE_INSTALL_PREFIX=./install -DparRSB_DIR=${INSTDIR}/lib/cmake/parRSB
        cmake --build build --target install
    - name: Test inclusion in another project with FetchContent
      run: |
        cd ./test/cmake/fetch_content
        cmake -S . -B build -DCMAKE_INSTALL_PREFIX=./install
        cmake --build build --target install
    - name: Block to allow inspecting failures
      run: sleep 120m
      if: ${{ failure() && inputs.debug_enabled }}
  dispatch:
    runs-on: ubuntu-latest
    needs: [unit, cmake]
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout actions
      uses: actions/checkout@v6
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ inputs.debug_enabled }}
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v4
      with:
        token: ${{ secrets.PARRSB_PY_PAT }}
        repository: thilinarmtb/parRSB.py
        event-type: parrsb_event
    - name: Block to allow inspecting failures
      run: sleep 120m
      if: ${{ failure() && inputs.debug_enabled }}
